version: "3.9"
   
services:
  db:
    image: mongo
    ports:
      - '27017:27017'

  backend:
    build:
        context: .
        dockerfile: Dockerfile-back
    command: sh -c 'cd ./tweet-moderation-back && npm install && node index.js '

    volumes:
      - .:/tweet-moderation-back
    ports:
      - "3001:3001"

    depends_on:
      - db

  frontend:
        build:
          context: .
          dockerfile: Dockerfile-front
        command: sh -c "cd ./tweet-moderation-front && npm install && npm start"
        volumes:
          - .:/tweet-moderation-front
        ports:
            - "3000:3000"
        depends_on:
          - db
          - backend